name: Deploy Blazor App to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x   # or 8.0.x if you switched

      - name: Install WASM workload
        run: dotnet workload install wasm-tools

      - name: Publish Blazor app
        run: dotnet publish TodoApp.csproj -c Release -o release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
